CapitalSoftWebSite/Controllers/TeamMembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CapitalSoftWebSite.Models;

namespace CapitalSoftWebSite.Controllers
{
    public class TeamMembersController : Controller
    {
        private AppDbContext db = new AppDbContext("DefaultConnection");

        // GET: TeamMembers
        public ActionResult Index()
        {
            var teamMembers = db.TeamMembers.Include(t => t.Image).Include(t => t.Language);
            return View(teamMembers.ToList());
        }

        // GET: TeamMembers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TeamMember teamMember = db.TeamMembers.Find(id);
            if (teamMember == null)
            {
                return HttpNotFound();
            }
            return View(teamMember);
        }

        // GET: TeamMembers/Create
        public ActionResult Create()
        {
            ViewBag.ImageId = new SelectList(db.Images, "ImageID", "ImageMimeType");
            ViewBag.LanguageID = new SelectList(db.Languages, "LanguageID", "Lang");
            return View();
        }

        // POST: TeamMembers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TeamMemberID,Firstname,Lastname,Position,LanguageID,ImageId")] TeamMember teamMember)
        {
            if (ModelState.IsValid)
            {
                db.TeamMembers.Add(teamMember);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ImageId = new SelectList(db.Images, "ImageID", "ImageMimeType", teamMember.ImageId);
            ViewBag.LanguageID = new SelectList(db.Languages, "LanguageID", "Lang", teamMember.LanguageID);
            return View(teamMember);
        }

        // GET: TeamMembers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TeamMember teamMember = db.TeamMembers.Find(id);
            if (teamMember == null)
            {
                return HttpNotFound();
            }
            ViewBag.ImageId = new SelectList(db.Images, "ImageID", "ImageMimeType", teamMember.ImageId);
            ViewBag.LanguageID = new SelectList(db.Languages, "LanguageID", "Lang", teamMember.LanguageID);
            return View(teamMember);
        }

        // POST: TeamMembers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TeamMemberID,Firstname,Lastname,Position,LanguageID,ImageId")] TeamMember teamMember)
        {
            if (ModelState.IsValid)
            {
                db.Entry(teamMember).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ImageId = new SelectList(db.Images, "ImageID", "ImageMimeType", teamMember.ImageId);
            ViewBag.LanguageID = new SelectList(db.Languages, "LanguageID", "Lang", teamMember.LanguageID);
            return View(teamMember);
        }

        // GET: TeamMembers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TeamMember teamMember = db.TeamMembers.Find(id);
            if (teamMember == null)
            {
                return HttpNotFound();
            }
            return View(teamMember);
        }

        // POST: TeamMembers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TeamMember teamMember = db.TeamMembers.Find(id);
            db.TeamMembers.Remove(teamMember);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CapitalSoftWebSite/Controllers/TechnologiesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CapitalSoftWebSite.Models;

namespace CapitalSoftWebSite.Controllers
{
    public class TechnologiesController : Controller
    {
        private AppDbContext db = new AppDbContext("DefaultConnection");

        // GET: Technologies
        public ActionResult Index()
        {
            return View(db.Technologies.ToList());
        }

        // GET: Technologies/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Technology technology = db.Technologies.Find(id);
            if (technology == null)
            {
                return HttpNotFound();
            }
            return View(technology);
        }

        // GET: Technologies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Technologies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TechnologyID,Name")] Technology technology)
        {
            if (ModelState.IsValid)
            {
                db.Technologies.Add(technology);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(technology);
        }

        // GET: Technologies/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Technology technology = db.Technologies.Find(id);
            if (technology == null)
            {
                return HttpNotFound();
            }
            return View(technology);
        }

        // POST: Technologies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TechnologyID,Name")] Technology technology)
        {
            if (ModelState.IsValid)
            {
                db.Entry(technology).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(technology);
        }

        // GET: Technologies/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Technology technology = db.Technologies.Find(id);
            if (technology == null)
            {
                return HttpNotFound();
            }
            return View(technology);
        }

        // POST: Technologies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Technology technology = db.Technologies.Find(id);
            db.Technologies.Remove(technology);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

CapitalSoftWebSite/Views/Shared/_AdminLayoutPage.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/admin/admin-style.css" />
    <link rel="stylesheet" href="~/Content/bootstrap.3.0.3.min.css" />
    <script src="~/Scripts/jquery-1.11.1.min.js"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/Content/admin/pages.css"  type="text/css"/>
</head>
<body>

    <div id="wrapper" class="active">

        <div id="sidebar-wrapper">
            <ul id="sidebar_menu" class="sidebar-nav">
                <li class="sidebar-brand">
                    <a id="menu-toggle">
                        Admin
                        <span id="main_icon" class="glyphicon glyphicon-align-justify"></span>
                    </a>
                </li>
            </ul>
            <ul class="sidebar-nav" id="sidebar">
                <li>
                    <a href="@Url.Action("Index", "TeamMembers")">
                        Team member
                        <span class="sub_icon glyphicon glyphicon glyphicon-user"></span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Technologies")">
                        Technology
                        <span class="sub_icon glyphicon glyphicon-link"></span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Projects")">
                        Project
                        <span class="sub_icon glyphicon glyphicon-link"></span>
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("Index", "Contacts")">
                        Contact
                        <span class="sub_icon glyphicon glyphicon-link"></span>
                    </a>
                </li>
            </ul>
        </div>

        <div id="page-content-wrapper">
            <div class="container-fluid">
                <div class="col-lg-12">
                    <div>
                        <p class="well-header lead">
                            Capital Soft
                            <a href="@Url.Action(actionName: "LogOff", controllerName: "Account", routeValues: new { area = ""})">
                                Log out
                                <span class="glyphicon glyphicon-log-out"></span>
                            </a>
                        </p>
                    </div>
                </div>
                <div class="main-content">
                    @RenderBody()
                </div>
            </div>
        </div>
    </div>


    <script>
        $("#menu-toggle").click(function (e) {
            e.preventDefault();
            $("#wrapper").toggleClass("active");
        });
    </script>



    <style>
        .well-header {
            color: white;
            min-height: 20px;
            padding: 17px;
            margin-bottom: 20px;
            background-color: #09192A;
            border: 1px solid #09192A;
            box-shadow: inset 0 1px 1px rgba(0,0,0,.05);
            border-left: 1px solid #7c7c7c;
        }

            .well-header a {
                color: white;
                font-size: 16px;
                padding-right: 250px;
            }

        .main-content {
            padding: 20px;
        }
    </style>
</body>
</html>

CapitalSoftWebSite/Views/Shared/_Layout.cshtml
@using CapitalSoftWebSite.Helpers

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <link rel="stylesheet" type="text/css" href="~/Content/font-awesome.css" />
    <link rel="stylesheet" href="~/Content/style.css" />
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,200i,300,300i,400,400i,600,600i,700,700i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato|Raleway|Roboto" rel="stylesheet">
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="fon-top-menu">
            <div class="logo col-md-2 pull-left ">
                <a><img src="~/Content/Images/logo55.png" alt="Logo"></a>
            </div>
            <div class="navbar-header col-md-6">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <div class="navbar-collapse fff collapse">
                    <ul class="nav navbar-nav navbnar-right">
                        <li class='@Html.IsActive("Home", "Index")'>@Html.ActionLink(Resources.Resource.Home, "", "")</li>
                        <li class='@Html.IsActive("Services", "Index")'>@Html.ActionLink(Resources.Resource.Services, "Index", "Services")</li>
                        <li class='@Html.IsActive("Portfolio", "Index")'>@Html.ActionLink(Resources.Resource.Portfolio, "Index", "Portfolio")</li>
                        <li class='@Html.IsActive("ContactAs", "Index")'>@Html.ActionLink(Resources.Resource.About, "Index", "ContactAs")</li>
                        <li class='@Html.IsActive("Team", "Index")'>@Html.ActionLink(Resources.Resource.Team, "Index", "Team")</li>
                    </ul>
                </div>
            </div>
            <div class=" social pull-left col-md-2">

                <ul>
                    <a href="">
                        <li class="line-social">
                            <i class="fa fa-facebook-official" aria-hidden="true"></i>
                        </li>
                    </a>
                    <a href="">
                        <li class="line-social line-social-1 ">
                            <i class="fa fa fa-twitter" aria-hidden="true"></i>
                        </li>
                    </a>

                    <a href="">
                        <li class="line-social line-social-1">
                            <i class="fa fa-linkedin" aria-hidden="true"></i>
                        </li>
                    </a>
                </ul>


            </div>

            <div class="language col-md-2">
                <ul id="lang">
                    <li class='@Html.IsActive("Home", "SetCulture")'>
                        @Html.ActionLink("eng", "SetCulture", "Home", new { lang = "en" }, null)
                      @*  <a href="@Url.Action("SetCulture", "Home", new { lang = "en"})">eng</a> |*@
                    </li>
                    <li class='@Html.IsActive("Home", "SetCulture")'>
                       @Html.ActionLink("rus", "SetCulture", "Home", new { lang = "ru"}, null)
                        @*<a href="@Url.Action("SetCulture", "Home", new { lang = "ru"})">rus</a> |*@
                    </li>
                    <li class='@Html.IsActive("Home", "SetCulture")'>
                        @Html.ActionLink("arm", "SetCulture", "Home", new { lang = "am"}, null)
                        @*<a href="@Url.Action("SetCulture", "Home", new { lang = "am"})">arm</a>*@
                    </li>
                </ul>
            </div>
        </div>
    </div>

    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


    <div id="modal-container" class="modal fade" tabindex="-1" role="dialog"></div>
    <script>

        $(function () {
            $('body').on('click', '.modal-link', function (e) {
                e.preventDefault();
                $(this).attr('data-target', '#modal-container');
                $(this).attr('data-toggle', 'modal');
            });
            $('body').on('click', '.modal-close-btn', function () {
                $('#modal-container').modal('hide');
            });
            $('#modal-container').on('hidden.bs.modal', function () {
                $(this).removeData('bs.modal');
            });

            $('#CancelModal').on('click', function () {
                return false;
            });
        });
    </script>

    <style>
        ul#menu li a {
            background: none;
            color: #999;
            padding: 5px;
            border-radius: 15px;
            text-decoration: none;
        }

            ul#menu li a.currentMenuItem {
                background-color: black;
                color: white;
            }
    </style>
</body>
</html>