CapitalSoftWebSite/Controllers/PortfolioController.cs
using CapitalSoftWebSite.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace CapitalSoftWebSite.Controllers
{
    public class PortfolioController : BaseController
    {
        [HttpGet]
        public async Task<ActionResult> Index()
        {
            IList<Project> list = await DbAdaptor.GetProjectsFullAsync(cultureName);
            return View(list);
        }


        [HttpGet]
        public async Task<ActionResult> More(int id)
        {
            ViewBag.Portfolio = true;

            Project model = await DbAdaptor.GetProjectAsync(id);
            if (model == null)
                return HttpNotFound();
            return PartialView("~/Views/Home/_More.cshtml", model);

           // return RedirectToAction("More", "Home", new { id = id });
        }
    }
}

CapitalSoftWebSite/Views/Portfolio/Index.cshtml
@model IEnumerable<CapitalSoftWebSite.Models.Project>

<div class="work" id="portfolio">
    @{
        if (Model != null)
        {
            int i = 0;
            foreach (var elem in Model)
            {

                <div class="container wight" id="#work">
                    @if (i % 2 == 0)
                    {
                        <div class="desktop col-md-6 col-sm-6 pull-right">
                            <img src="@Url.Action("GetImage", "Home", new { elem.Images.First().ImageID })" width="100%" alt="">
                        </div>
                    }
                    else
                    {
                        <div class="desktop col-md-6 col-sm-6 pull-left">
                            <img src="@Url.Action("GetImage", "Home", new { elem.Images.First().ImageID })" width="100%" alt="">
                        </div>
                    }
                    <div class="work-info col-md-6 col-sm-6">
                        <h1>@elem.Name</h1>
                        <p>@elem.Description</p>
                        <h1>@Resources.Resource.Technologies</h1>
                        <ul>
                            @if (elem.Technologies != null)
                            {
                                foreach (var t in elem.Technologies)
                                {
                                    <li>@t.Name</li>
                                }
                            }
                        </ul>
                        <div class="line"></div>
                        <div class="container">
                            @*<button class="btn btn-primary more-btn" data-toggle="modal" data-target="#@elem.ProjectID">
                                    More
                                </button>*@
                            @*@{ Html.RenderPartial("More", elem); }*@
                            @Html.ActionLink("More", "More", "Portfolio", new { id = elem.ProjectID }, new { @class = "modal-link btn btn-success" })
                        </div>
                    </div>
                </div>
                ++i;
            }
        }
    }
</div>